name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup local.properties
        run: echo "sdk.dir=$ANDROID_HOME" >> local.properties
      - uses: snyk/actions/setup@master
      - run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
